// export {default as Home} from './home.svg';
// export {default as Home2} from './home2.svg';
// export {default as mainLogo} from './back.png';

export {default as puppy} from './puppy.svg';
export {default as puppyOff} from './puppy_off.svg';
export {default as bags} from './bags.svg';
export {default as bagsOff} from './bags_off.svg';
export {default as building} from './building.svg';
export {default as buildingOff} from './building_off.svg';
export {default as shopping} from './shopping.svg';
export {default as shoppingOff} from './shopping_off.svg';
export {default as backspace} from './backspace.svg';
export {default as search} from './search.svg';
export {default as settings} from './settings.svg';
export {default as x} from './x.svg';
export {default as bell_black} from './bell_black.svg';
export {default as bell_white} from './bell_white.svg';
export {default as logo} from './logo.svg';
export {default as profile} from './profile.svg';
export {default as send} from './send.svg';
// export {default as searchIcon} from '../icons/search.png';
// export {default as notificationIcon} from '../icons/bell_black.png';
